src/components/molecules/CrossChainChart/styles.scss, src/components/molecules/VAACountChart/styles.scss, src/pages/Home/Statistics/index.tsx, src/pages/Home/Statistics/styles.scss, src/pages/Home/index.tsx, src/styles/_containers.scss, src/styles/globals.scss
- Add `card-container` scss mixin.
- Add `Statistics` component to the `Home` page with some hardcoded data.
=>  feat: add card-container mixin

src/components/atoms/NavLink/index.tsx, src/components/atoms/index.tsx, src/components/molecules/Footer/index.tsx, src/components/molecules/Header/index.tsx
This PR fixes a bug found by Ricardo: when switching routes, the page stays at the same scrolling position, so if you for example click on a Footer link, you go successfully to the new route, but it's like you scrolled all the way down.
With this PR, after a redirect, we will always be on top
=> Fix navigation scroll not going up

src/components/molecules/CrossChainChart/index.tsx, src/components/molecules/TransactionHistoryChart/index.tsx, src/i18n/locales/en.js, src/pages/Txns/Information/index.tsx
- Replaced 'Chains' for 'Volume' on cross chain chart options.
- Deleted the `/ ENS` string from the search because ENS won't be available on v1.
- Format transaction history chart labels (`200K` instead of `200000`, `14.1M` instead of `14091231`)
- Deleted the NFT section from the txs table
=> Fix little UI stuff

.github/workflows/playwright.yml, src/components/molecules/CrossChainChart/Chart.tsx, src/components/molecules/CrossChainChart/index.tsx, src/components/molecules/CrossChainChart/styles.scss, src/index.scss
- Makes the x-chain-activity endpoint be retried twice in case of server error response.
- Set a min width of the webapp to 360px to prevents bugs for forced small resolutions.
- Turn off the playwright testing job.
- Refactor the responsiveness of the sankey chart to match Figma better.
BIG DESKTOP
SMALL DESKTOP
iPad Mini
iPhone Pro
=> Refactor sankey-chart responsiveness

src/components/molecules/TransactionHistoryChart/index.tsx
Fixes 129
- Tx history graph now should display `00:XX` hours instead of `24:XX` hours in the tooltip.
=> fix: Tx history graph should display correcto 24h

package.json, src/components/molecules/CrossChainChart/Chart.tsx, src/components/molecules/CrossChainChart/StickyInfo.tsx, src/utils/hooks/useOutsideClick.ts, yarn.lock
- Changed the sankey chart from an animation to a fixed image (with this, the sankey chart looks amazing on every device without compromising performance as it was before).
- Did the requested changes for the bottom sheet mobile component.
--
Those bottom sheet changes are the following:
- It is now draggable down for it to be closed.
- It doesn't close if you press on it while its open anymore, it now closes when you press outside of it while open.
https://github.com/XLabs/wormscan-ui/assets/41705567/8fa140ee-a712-457b-9796-5c12b7d22268
- If the device is a big device where the bottom sheet can be shown at full along the sankey chart at full (like an iPad Air or a non-fullscreen desktop), it wont close when yo press outside of it (because you can use the vertical space to see it all …
=> Better mobile bottom sheet and better performance

src/components/molecules/CrossChainChart/Chart.tsx, src/components/molecules/CrossChainChart/index.tsx, src/components/molecules/CrossChainChart/styles.scss
This PR
- Fixes the following bug: #161 .
- Removes the "Volume" tab on testnet because testnet assets are not worth money (only transaction available now).
- Adds the volume data for small desktop devices that were not able to see that data (>1024px & <1440px)
=> Improve Cross Chain Chart for testnet and small desktops

src/components/atoms/Pagination/index.tsx, src/components/atoms/Pagination/styles.scss, src/components/molecules/CrossChainChart/Chart.tsx, src/components/molecules/CrossChainChart/styles.scss
This PR implements pagination on the cross chain activity chart for users to be able to see the transactions/volume information for every chain including the small ones instead of only the top 10 ones
=> Add pagination to CrossChainChart to see every chain info

src/components/molecules/Header/index.tsx, yarn.lock
- If I was on the details of a transaction on mainnet and selected mainnet on the network selector, the page was getting stuck on a infinite loader, and, if I selected testnet, it tried to search for the same txHash on testnet (which its never going to be found)
- If I was on the 'search not found' page and I switched network, the search not found page was refreshed but on the different network
https://github.com/XLabs/wormscan-ui/assets/41705567/4ce1cbf8-6650-4b4b-ab89-ead607f7e89f
- If I'm on the details of a transaction on mainnet and select mainnet, nothing happens. And if I select testnet, it moves the user to the transactions list.
- If I'm on the 'search not found' page and I switch network, It moves me to the home.
https://github.com/XLabs/wormscan-ui/assets/41705567/76cb0f46-de09- …
=> Fix two navigation feedbacks

package.json
By removing some modules that we are not using right now (deps of `@certusone/wormhole-sdk`) from the `build` we reduced the bundle size by **64.78%**
Before:
After:
=> build: reduce bundle size

src/components/atoms/SignatureCircle/index.tsx, src/pages/Tx/Information/Overview/index.tsx
Fixes 217
- Display full circle when is on `testnet` network with only 1 guardian
=> fix(217): show full circle in testnet

src/components/atoms/Tag/index.tsx, src/components/atoms/Tag/styles.scss, src/components/molecules/Footer/index.tsx, src/components/molecules/Footer/styles.scss, src/consts.ts, src/i18n/locales/en.js
Fixes 233, 234
- Add new content for the `Footer` component on desktop and mobile.
Desktop:
Mobile:
=> feat(233,234): add new footer content and styling

src/components/atoms/Pagination/index.tsx, src/components/atoms/Pagination/styles.scss, src/pages/Txs/Information/index.tsx, src/pages/Txs/Information/styles.scss, src/pages/Txs/index.tsx
Fix 239
- Add 5 page numbers buttons into the pagination component.
Desktop:
Mobile:
This is how is displayed when the `txs` are not filtered by any
=> feat: add 5 visible page numbers

src/components/organisms/Table/styles.scss
- Origin apps are inline on mobile
- Text with the same size in mobile and desktop
=> Origin apps are inline on mobile

src/components/molecules/Header/Search/index.tsx, src/pages/Tx/index.tsx, src/pages/Txs/Information/index.tsx, yarn.lock
One transaction hash can have multiple VAAs associated with it. We were not handling that possibility. This PR fixes that.
- Prioritize txHash search instead of VAA-ID search: On the transactions list, when a user presses on a transaction, it goes to the transaction hash detail instead of going to the VAA-ID detail.
- If the result of a txHash search has multiple VAAs, show them all, one below each other. _(don't worry about it looking kinda overkill with the info, the design for this will change soon)_
**BEFORE**
**AFTER**
=> Better txHash search support

src/components/atoms/Pagination/index.tsx, src/components/molecules/CrossChainChart/Chart.tsx, src/components/molecules/CrossChainChart/StickyInfo.tsx, src/components/molecules/CrossChainChart/index.tsx, src/components/molecules/CrossChainChart/styles.scss, src/components/molecules/ScoreCard/index.tsx
- Sankey chart modification so source information is always on the left and target information is always on the right. When it's showing targets information it makes the right side clickable and the pagination moves to the right.
- Changed order for wormhole stats on main page
**DESKTOP**
**MOBILE**
**WH STATS TESTNET**
=> Feat: Targets always at right on cross-chain chart

src/components/molecules/CrossChainChart/Chart.tsx, src/components/molecules/CrossChainChart/index.tsx, src/components/molecules/CrossChainChart/styles.scss
Last cross chain activity chart design implemented.
- On testnet, we don't show a switch-style button for the 'type' of graph because there's only one option (transactions), so we show it as an informative text instead.
- Source <-> Target button redesigned.
- Sankey chart styles changed.
=> Sankey Chart last design implemented

src/components/molecules/Header/index.tsx, src/pages/Tx/Information/Details/index.tsx, src/pages/Tx/Information/Overview/index.tsx, src/pages/Txs/index.tsx
- Show N/A when the symbol is not found.
=> Fix when symbol not found, show N/A

src/pages/Tx/Information/RawData/index.tsx, src/pages/Tx/Information/index.tsx, src/pages/Tx/index.tsx, src/utils/fetchWithRPCsFallthrough.ts, src/utils/wh-connect-rpc.ts
This PR adds support to see Wormhole-Connect related information on RPCs (this means, when a user just makes a transaction and there is no VAA emitted yet)
Also, it fixes some bugs on non-vaa transactions (for example: SUI transactions were crashing the app, and redeem amount sometimes was showing a ridiculously high number)
=> RPCs info support for wh-connect and fixes

src/pages/Tx/index.tsx
Sometimes the API respond without a `tokenAmount` or `symbol` for CCTP transactions.
This PR patches those cases getting that info from the payload and assuming USDC with 6 decimals.
=> Fix CCTP amounts when tokenAmount is not there

src/api/search/Search.ts, src/pages/Tx/index.tsx, src/utils/fetchWithRPCsFallthrough.ts
When a transaction is just made, the Portal Bridge and the Wormhole Connect apps have a link to come directly to the wormholescan to see the transaction.
The problem was: The tx was not always available when pressing on the 'see on wormholescan', that only works immediately if the chain its EVM, on other cases like Solana, the not found was being shown:
https://github.com/XLabs/wormscan-ui/assets/41705567/042e9f60-5864-4018-bd94-72d4cb39f8ca
☝🏼
This PR fixes those cases by retrying at least 4 times before sending the user to the not found page. That fixes the majority of not found for recently made transactions:
👇🏼 
https://github.com/XLabs/wormscan-ui/assets/41705567/7fcd57b4-7fd8-4280-986d-d0341fd812e4
---
The endpoints "https://relayer.stable.io/v1/relays" and …
=> Better tx handling and cctp endpoint fix

package.json, src/analytics.ts, src/components/molecules/CrossChainChart/Chart.tsx, src/components/molecules/CrossChainChart/index.tsx, src/components/molecules/Header/Search/index.tsx, src/components/molecules/TransactionHistory/index.tsx, src/components/organisms/SearchNotFound/Error400/index.tsx, src/components/organisms/SearchNotFound/Error500/index.tsx, src/components/organisms/SearchNotFound/Error502/index.tsx, src/components/organisms/SearchNotFound/Error503/index.tsx, src/components/organisms/SearchNotFound/ErrorGeneral/index.tsx, src/navigation/index.tsx, src/pages/NotFound/index.tsx, src/pages/Tx/Information/Tabs/index.tsx, src/pages/Tx/Information/index.tsx, src/pages/Tx/index.tsx, src/pages/Txs/index.tsx, src/utils/analyticsLinkTracker.tsx
This PR adds analytics tracking for different events:
- cross chain chart usage
- transaction history usage
- links clicked
- searches done (not what is being search, only on what network)
- tx details views election (Overview/RawData and Overview/Detailed)
- tx details appId, source and target
=> Add analytics tags

src/pages/Tx/index.tsx, src/utils/fetchWithRPCsFallthrough.ts
This PR adds support to see status of generic relayers transactions before there's a VAA emitted using RPCs
=> Add generic relayers support on RPCs

src/api/Client.ts, src/api/guardian-network/GuardianNetwork.ts, src/components/molecules/Header/Search/index.tsx, src/pages/Tx/index.tsx
This PR unifies the searchbar so the user can paste a txHash/vaaID/address of any network and it will redirect him to the correct one.
We did this because a lot of users were opening wormholescan and pasting a testnet txHash without changing the network to TESTNET first.
With this, those transactions will be found. (same if a user its on testnet and searches for a mainnet txHash/VaaID/address)
https://github.com/XLabs/wormscan-ui/assets/41705567/94ff386a-94a7-4109-90ba-4f6cfc8083a8
=> Unified networks SearchBar

src/components/molecules/Header/index.tsx, src/components/molecules/Header/styles.scss, src/consts.ts, src/i18n/locales/en.js, src/pages/Tx/Information/Summary/VerifyRedemption/index.tsx
- wormhole.com added.
- VERIFY REDEMPTION button changed to RESUME TRANSACTION.
=> wormhole.com added

src/pages/Tx/Information/index.tsx, src/utils/analyticsLinkTracker.tsx
This PR makes a change so:
- every URL pressed on wormholescan gets detected (dynamic urls, for example, the ones that appear after a state change, were not being tracked)
- findRedeem event gets tracked with its info
=> Analytics: track all urls and findRedeem

src/components/molecules/CrossChainChart/Chart.tsx, src/components/molecules/CrossChainChart/index.tsx
On the cross-chain-activity chart (aka sankey chart), when the user switched between "Volume/Transactions", the chain selected was always the first one instead of maintaining the chain that was previously selected. This PR changes that.
BEFORE
https://github.com/XLabs/wormscan-ui/assets/41705567/7fcd9f7f-7274-4266-ac5a-d8867e7e45cc
AFTER
https://github.com/XLabs/wormscan-ui/assets/41705567/7938c2b3-3815-4835-8c00-2cc411c30a40
=> Maintain chain selected on volume/txn change

src/api/guardian-network/types.ts, src/pages/Tx/Information/AdvancedView/Details/RelayerDetails/index.tsx, src/pages/Tx/Information/AdvancedView/Details/index.tsx, src/pages/Tx/Information/Overview/RelayerOverview/index.tsx, src/pages/Tx/Information/Overview/index.tsx, src/pages/Tx/Information/index.tsx, src/pages/Txs/Information/Filters/index.tsx
- Added tooltip for duplicate VAA ID.
- Chain Scroll added to txs filters.
=> Tooltip for vaa id duplicated, Scroll added in filters

src/utils/environment.ts
Terraform Labs is deprecating phoenix-lcd.terra.dev. https://lcd-terra.tfl.foundation should be used instead
=> Replace Terra2 RPC

src/api/guardian-network/types.ts, src/pages/Tx/Information/AdvancedView/Details/RelayerDetails/index.tsx, src/pages/Tx/Information/AdvancedView/Details/index.tsx, src/pages/Tx/Information/AdvancedView/index.tsx, src/pages/Tx/Information/Overview/RelayerOverview/index.tsx, src/pages/Tx/Information/Overview/index.tsx, src/pages/Tx/Information/index.tsx, src/pages/Tx/index.tsx, src/utils/genericRelayerVaaUtils.ts
This PR refactors the way wormholescan handles standard relayer transactions.
Originally, all the relayers logic was 100% frontend, so we needed to get some information with the API and from there get everything else, so all the logic ended up being in a child component instead of the one with all the txn logic (`Tx`).
Nowadays we can get everything we need from the API and the logic had to be where everything else is.
With this refactor the standard relayer transactions are not going to show a Loader anymore. It will load everything at the same time. It also should fix some inconsistencies with the Arkham addresses tooltip.
=> Refactor Standard Relayer handling

src/api/guardian-network/types.ts, src/pages/Tx/Information/AdvancedView/Details/index.tsx, src/pages/Tx/Information/Overview/index.tsx, src/pages/Tx/Information/index.tsx, src/pages/Tx/index.tsx
Adds initial support for Portal Bridge NFTs, with and without IPFS.
If the request fails, we try to fetch again with a CORS Proxy, that fixes 80% of the problems, but some URLs have anti-cors-proxies, so we'll need to move the calls to the BFF instead of doing them from the client.
Also, this PR adds support for image-type NFTs, so support for 3D/Video/Audio should be added.
=> Add Portal NFTs initial support

src/api/guardian-network/GuardianNetwork.ts, src/consts.ts, src/pages/Tx/Information/AdvancedView/index.tsx, src/pages/Tx/Information/Overview/index.tsx, src/pages/Tx/Information/index.tsx, src/pages/Tx/index.tsx, src/utils/fetchWithRPCsFallthrough.ts, yarn.lock
This PR adds support for cases where there's not a VAA yet but there are some observations to it. So instead of showing the user "we have no data" we can at least show the signatures we have and from what guardians they are.
---
With RPC data (RPCs were able to get at least some of the tx information):
https://github.com/XLabs/wormscan-ui/assets/41705567/9a73a1b3-a303-40a5-8e86-e673e72fa635
-
With no data (nor API or RPC has any data for the txn):
=> Add observations support

src/pages/Tx/index.tsx
This PR improves the observations handling:
- When the `/operations` endpoint has a response, but it doesn't have the `vaa` field (no vaa emitted yet), we call the observations endpoint to get the current signatures and we display the regular UI with the signatures and information.
- When the `/operations` endpoint has no response for a txHash, we call the observations endpoint and we show a only-data screen with the signatures, the observations, the txHash and the vaa-id.
with operations without vaa
without operations
=> Improve observations handling

package.json, src/api/guardian-network/GuardianNetwork.ts, src/components/molecules/ProtocolsActivity/index.tsx, src/components/molecules/WormholeStats/index.tsx, src/components/molecules/WormholeStats/styles.scss, src/pages/Analytics/WToken/Summary.tsx, src/pages/Analytics/WToken/index.tsx, src/pages/Analytics/WToken/styles.scss, src/utils/crypto.ts, yarn.lock
- This PR unifies the Portal Token Bridge and Connect data for protocol stats (both in home for "Top 5 Protocols" and in "Protocol Stats" section) and also for Protocols Activity graph.
- Also, it adds "Flip Numbers" to the W Token price along with the home Wormhole stats. (currently kinda useless as those have caches and flip numbers won't be seen, only at first load ⚠️)
BEFORE - AFTER [1]
BEFORE - AFTER [2]
FLIP NUMBERS
https://github.com/user-attachments/assets/64be9d78-29a7-459e-90c7-f9c52f28ac3e
=> Flipping numbers for some stats and front unification of portal and connect data

src/api/guardian-network/GuardianNetwork.ts, src/api/guardian-network/types.ts, src/components/molecules/ProtocolsStats/index.tsx, src/components/organisms/ChainActivity/index.tsx, src/components/organisms/ChainActivity/styles.scss, src/components/organisms/TokenActivity/Chart.tsx, src/components/organisms/TokenActivity/index.tsx, src/i18n/locales/en.js
This PR:
- Replaces the word `Transactions` for `Transfers` in a lot of places (cross-chain chart, chain activity chart, etc)
- Changes the Mayan endpoint used to get the info for Protocol Stats (with the new endpoint, we cannot show percentage of change for 24H volume/transfers, so Mayan wont show it)
- Changes the labels for Chains Activity chart
=> Better labels. Mayan protocol stats fixed.

src/components/molecules/CrossChainChart/Chart.tsx, src/components/molecules/ProtocolsActivity/index.tsx, src/components/molecules/ProtocolsStats/index.tsx
- "+" removed when the variation is 0%.
- "N/A" removed if it's not possible to calculate the variation.
- Sankey chart - show page 1 item 1 if the selected chain is not found.
- After selecting a Protocol the modal will close.
=> Bugs fixed

src/pages/Submit/Step2.tsx, src/pages/Submit/index.tsx
- When the user first loads a txHash, vaa ID or raw vaa, automatically start parsing
- When the user its in the "finished parsing" state, the "Prev Step" button maintains the same screen but removes the last finished parsed element so user can reparse it
=> Fixes for Submit your Protocol

src/components/atoms/Tooltip/styles.scss, src/pages/Governor/index.tsx, src/pages/Governor/styles.scss, src/pages/Txs/Top/index.tsx, src/pages/Txs/Top/styles.scss, src/utils/governorUtils.tsx
#840 
- Styles changes.
- Default view changed.
- Tooltips fixed on mobile.
- Elements rearranged on mobile.
=> Governor - enhancements

src/components/organisms/ChainActivity/index.tsx, src/pages/Analytics/WToken/RecentTransactions.tsx
- The page explodes because the complete information is not available in the endpoint.
=> W token page fixed & volumen changed by volume - PROD

.eslintrc.json, src/api/guardian-network/types.ts, src/pages/Tx/Information/Overview/index.tsx, src/pages/Tx/Information/index.tsx, src/pages/Tx/index.tsx, src/utils/txPageUtils.tsx
This PR adds a "Release Time" for the transaction details of transactions that have IN GOVERNORS status (when possible)
=> Add release time for IN GOVERNORS transactions

src/components/molecules/StatusBadge/index.tsx, src/pages/Governor/index.tsx, src/pages/Tx/Information/Overview/index.tsx, src/pages/Tx/Information/ProgressView/index.tsx, src/pages/Tx/Information/Summary/GetRedeem/index.tsx, src/pages/Tx/Information/Summary/VerifyRedemption/index.tsx, src/pages/Tx/Information/Summary/styles.scss
[WS-106](https://xlabs-xyz.atlassian.net/browse/WS-106) [WS-111](https://xlabs-xyz.atlassian.net/browse/WS-111)
[WS-106]: https://xlabs-xyz.atlassian.net/browse/WS-106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
- Governor page - remove chains without info.
- "redeem" renamed.
- Bug with "resume tx" button on mobile, fixed.
[WS-111]: https://xlabs-xyz.atlassian.net/browse/WS-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Governor page fixed & renames

src/pages/Tx/index.tsx, src/utils/mayan.ts
This PR adds logic to call Mayan endpoint for a specific configuration (Mayan MCTP where action its 1 or 3) and show all the information that we weren't showing
=> Add Mayan MCTP extra info

src/components/organisms/TokenActivity/index.tsx, src/pages/Tx/Information/Overview/index.tsx
[WS-258](https://xlabs-xyz.atlassian.net/browse/WS-258) [WS-262](https://xlabs-xyz.atlassian.net/browse/WS-262)
- Don't show USDC by default in Top 10 Tokens Transferred.
- Executed Tx Hash relocated in the tx details.
https://github.com/user-attachments/assets/b87f2aab-1fc3-4413-a71d-f31a153ef053
https://github.com/user-attachments/assets/465c3abe-cc82-4321-876d-2d7d40b1da4e
[WS-258]: https://xlabs-xyz.atlassian.net/browse/WS-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WS-262]: https://xlabs-xyz.atlassian.net/browse/WS-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Executed Tx Hash relocated & Tokens Transferred list fixed

package.json, src/pages/Submit/index.tsx, src/pages/Tx/index.tsx, src/pages/VaaParser/index.tsx, src/utils/cryptoToolkit.ts
This PR adds a check for Wormhole Liquidity Layer transactions (those with payloadId = 11) so the token and the amount can be shown
=> Add support for source token info for WH Liquidity Layer

src/api/guardian-network/types.ts, src/pages/Tx/Information/Overview/index.tsx, src/pages/Tx/Information/index.tsx, src/pages/Tx/index.tsx, src/utils/txPageUtils.tsx
This PR adds more support for **Mayan Shuttle + Wormhole Liquidity Layer** transactions.
- For those with `payloadId = 1` that contain target token information, the correct target token and amount will be shown.
=> Add more Mayan Shuttle support

src/api/guardian-network/GuardianNetwork.ts, src/components/atoms/ProtocolIcon/index.tsx, src/components/molecules/ProtocolsStats/index.tsx, src/consts.ts, src/pages/Tx/Information/index.tsx, src/pages/Tx/index.tsx, src/utils/filterUtils.tsx
This PR deletes all the patching logic that we had to rename FAST_TRANSFERS to WORMHOLE_LIQUIDITY_LAYER and SWAP_LAYER to MAYAN_SHUTTLE
Now, they are called "Wormhole Settlements" and "Mayan Shuttle" and come like that directly from API.
=> Wormhole Settlements fixes
