XLabs/wormscan-ui

- .gitignore
- README.md
- package.json
- src/App.scss
- src/App.tsx
- src/components/atoms/Loader/index.tsx
- src/components/atoms/Loader/styles.scss
- src/components/molecules/CrossChainChart/styles.scss
- src/components/molecules/VAACountChart/Chart.tsx
- src/components/molecules/VAACountChart/index.tsx
- src/components/molecules/VAACountChart/styles.scss
- src/components/molecules/index.tsx
- src/globals.scss
- src/navigation/index.tsx
- src/pages/Home/index.tsx
- yarn.lock
This PR implements a **VAAs count by blockchain** treemap chart, which gets the information from the APIs using a Wormscan SDK method.
- Added the [wormscan-sdk](https://github.com/XLabs/wormscan-sdk/tree/develop) library as a dependency along with [react-query](https://react-query-v3.tanstack.com/) and [react-apexcharts](https://apexcharts.com/react-chart-demos/).
- Reordered some code.
- Created `Loader` component.
- Implemented the `VAAs Count Chart` using Wormscan SDK + React Query + Apex Charts.
You can access the app [here](http://staging.wormscan.io/)
The design of the Wormscan UI it's not defined yet. Everything can and possibly will change. The chart implemented here may not be used at all on the app later. _This development it's to have everything we need to work on real stuff …
> VAAs count chart implemented

- .github/workflows/gh-pages.yml
- CNAME
- package.json
With this PR, every time the `develop` branch receives a push (direct push or pull requested merged on it), it will trigger a github action which will build the app, add the custom domain config to the build, and push the built folder to the `gh-pages` branch.
When that happens, another github action will be fired which deploys the app into the our page: http://staging.wormscan.io/
> Add Page and custom domain workflow configuration

- package.json
- src/App.scss
- src/components/atoms/Loader/styles.scss
- src/components/atoms/index.tsx
- src/components/molecules/CrossChainChart/index.tsx
- src/components/molecules/CrossChainChart/styles.scss
- src/components/molecules/Header/styles.scss
- src/components/molecules/VAACountChart/index.tsx
- src/components/molecules/VAACountChart/styles.scss
- src/globals.scss
- src/pages/Home/index.tsx
- yarn.lock
- Added the Figma's colors palette (the name of the colors can change on following PRs).
- Added the filters UI for the CrossChain chart container.
- Cleaned some code.
> Add colors palette & cross-chain filters UI

- .env.develop
- .env.development
- .gitignore
- README.md
- package.json
- src/App.tsx
- src/api/Client.ts
- src/components/molecules/VAACountChart/Chart.tsx
- src/components/molecules/VAACountChart/index.tsx
- yarn.lock
> update sdk references

- .github/workflows/gh-pages.yml
> set up NODE_ENV=development for staging deploy

- src/App.tsx
- src/index.html
- src/index.scss
- src/layouts/BaseLayout/index.tsx
- src/pages/Home/Hero/styles.scss
- Fix Hero section styles to match the design per Figma.
- Fix the Footer to always be on the bottom of the page.
> fix: Hero styling

- src/i18n/locales/en.js
- src/pages/Home/Hero/index.tsx
- src/pages/Home/Hero/styles.scss
- src/styles/_button.scss
[UI] Update Hero Section as per Figma
> fix: Hero UI

- src/components/molecules/Footer/index.tsx
- src/components/molecules/Footer/styles.scss
- src/components/molecules/Header/index.tsx
- src/components/molecules/WormholeBrand/styles.scss
- src/i18n/locales/en.js
[UI] Update Footer Section as per Figma
> fix: Footer UI

- package.json
- src/components/atoms/Select/index.tsx
- src/components/atoms/Select/styles.scss
- src/components/atoms/index.tsx
- src/components/molecules/CrossChainChart/index.tsx
- src/components/molecules/CrossChainChart/styles.scss
- yarn.lock
[UI] Fix Select Component
- Refactor and Abstract
- Styling
> fix: Select Component

- package.json
- src/components/atoms/ToggleGroup/index.tsx
- src/components/atoms/ToggleGroup/styles.scss
- src/components/atoms/index.tsx
- src/components/molecules/CrossChainChart/index.tsx
- src/components/molecules/CrossChainChart/styles.scss
- src/pages/Home/JoinUs/styles.scss
- src/pages/Home/index.tsx
[UI] Fix ToggleGroup Component
- Refactor
- Styling
- Remove **VAAs count by blockchain** section
- Fix **Join us** section
- Remove `@radix-ui/react-dropdown-menu` dep
> fix(ToggleGroup): add ToggleGroup Component

- src/components/molecules/CrossChainChart/styles.scss
- src/components/molecules/TopAssetListItem/index.tsx
- src/components/molecules/TopAssetListItem/styles.scss
- src/components/molecules/TopChainListItem/index.tsx
- src/components/molecules/TopChainListItem/styles.scss
- src/components/molecules/index.tsx
- src/components/organisms/TopList/index.tsx
- src/components/organisms/TopList/styles.scss
- src/components/organisms/index.tsx
- src/i18n/locales/en.js
- src/pages/Home/Hero/styles.scss
- src/pages/Home/TopLists/index.tsx
- src/pages/Home/TopLists/styles.scss
- src/pages/Home/index.tsx
- src/utils/number.ts
[UI] Add Top Lists Section
- Top Chain List
- Top Asset List
> feat(toplist): add top chain list and top asset list

- src/components/molecules/SearchBar/index.tsx
- src/components/molecules/SearchBar/styles.scss
- src/components/molecules/index.tsx
- src/i18n/locales/en.js
- src/pages/Home/Hero/styles.scss
- src/pages/Txns/Top/index.tsx
- src/pages/Txns/Top/styles.scss
- Add Search bar component
- Fix styles
> feat: add Search bar component

- package.json
- src/components/organisms/Tabs/index.tsx
- src/components/organisms/Tabs/styles.scss
- src/components/organisms/index.tsx
- src/i18n/locales/en.js
- src/pages/Txns/Information/index.tsx
- src/pages/Txns/Top/styles.scss
- src/pages/Txns/index.tsx
- yarn.lock
> feat: add tabs component

- package.json
- patches/@radix-ui+react-select+1.2.1.patch
- src/components/molecules/CrossChainChart/Chart.tsx
- src/components/molecules/CrossChainChart/index.tsx
- src/components/molecules/CrossChainChart/styles.scss
- src/components/molecules/Footer/styles.scss
- src/components/molecules/Header/index.tsx
- src/components/molecules/Header/styles.scss
- src/components/molecules/TopAssetListItem/styles.scss
- src/components/molecules/TopChainListItem/index.tsx
- src/components/molecules/TopChainListItem/styles.scss
- src/components/organisms/Tabs/styles.scss
- src/i18n/locales/en.js
- src/index.html
- src/index.scss
- src/pages/Home/Statistics/index.tsx
- src/pages/Home/Statistics/styles.scss
- src/pages/Txns/Top/styles.scss
- yarn.lock
This PR implements Responsive Design on Wormscan UI, so the webapp can be used on a tablet or a mobile device.
- Added responsive designs using existing breakpoint.
- Added patch-package to patch radix-select behavior (mobile devices were triggering options on scroll [**](https://github.com/radix-ui/primitives/issues/1641)).
- Implemented header mobile design (hamburger menu instead of visible items).
**BEFORE**
https://user-images.githubusercontent.com/41705567/227240960-ee6877ab-e7d3-4739-bd82-7a0b76247572.MP4
**AFTER**
https://user-images.githubusercontent.com/41705567/227241568-21a50a71-46c7-4fa9-862a-2fffcaba8315.MP4
> Implement Responsive design

- .vscode/settings.json
- src/assets/background-mobile-menu.svg
- src/components/molecules/Header/index.tsx
- src/components/molecules/Header/styles.scss
- src/components/molecules/JoinUs/styles.scss
- Fix Menu mobile
- Fix the Join us section on mobile
> fix: join us section and menu mobile

- package.json
- src/components/organisms/Table/index.tsx
- src/components/organisms/Table/styles.scss
- src/components/organisms/index.tsx
- src/pages/Txns/Information/index.tsx
- src/pages/Txns/Information/styles.scss
- yarn.lock
> feat: add table component

- src/components/molecules/Footer/index.tsx
- src/components/molecules/Footer/styles.scss
> fix: footer mobile

- src/components/molecules/Header/index.tsx
- src/components/molecules/Header/styles.scss
- src/pages/Home/TopLists/index.tsx
- Remove unused links
- Add Hover effect to links
> fix: header styling & remove unused links

- src/components/atoms/NavLink/index.tsx
- src/components/atoms/NavLink/style.scss
- src/components/molecules/Footer/index.tsx
- src/components/molecules/Footer/styles.scss
- src/components/molecules/Header/styles.scss
- src/i18n/locales/en.js
- Fix `Footer` styles on mobile and desktop view
- Fix `NavLink` styles on hover
- Change `join` to `Join` text
> fix: footer styling mobile and desktop

- src/components/atoms/ToggleGroup/styles.scss
- src/components/molecules/CrossChainChart/styles.scss
- Fix `Tabs / Toggle` styles on the mobile view 
- Fix `Tabs / Toggle` border styles.
> fix: Tabs on mobile view styles

- package.json
- src/components/molecules/TransactionHistoryChart/index.tsx
- src/components/molecules/TransactionHistoryChart/styles.scss
- src/pages/Home/Statistics/index.tsx
- src/pages/Home/Statistics/styles.scss
- yarn.lock
The "transaction history" chart was using hardcoded mocked data because there were no endpoints for that.
The endpoint is working now so we were able to connect the chart to the real data.
---
_INFO: There is one bug (reported here [#238](https://github.com/wormhole-foundation/wormhole-explorer/issues/238)) that affects the "1 month" selection. Only 10% of the times the endpoint responds for the "month" selection, and when it does, it comes with almost empty data for the last days (as you can see on screenshot below) ⚠️, that should be fixed by API team._
---
> Connect last txns real data

- .github/workflows/playwright.yml
- .gitignore
- package.json
- playwright.config.ts
- src/components/molecules/CrossChainChart/index.tsx
- src/components/molecules/Footer/index.tsx
- src/components/molecules/Header/index.tsx
- src/components/molecules/JoinUs/index.tsx
- src/components/organisms/TopList/index.tsx
- src/pages/Home/Hero/index.tsx
- src/pages/Home/Statistics/index.tsx
- tests/footer.spec.ts
- tests/header.spec.ts
- tests/home.spec.ts
- tests/joinUs.spec.ts
- yarn.lock
- Add Playwright basic setup
- Add Playwright end-to-end basic tests
- Add `playwright.yml` Github action
- Add `data-testid` for some elements
Playwright: https://playwright.dev/
> feat: Add Playwright End to End basic setup & tests

- src/components/atoms/ToggleGroup/index.tsx
- src/components/molecules/ScoreCard/index.tsx
- src/components/molecules/ScoreCard/styles.scss
- src/pages/Home/Statistics/index.tsx
- src/pages/Home/Statistics/styles.scss
- tests/home.spec.ts
- yarn.lock
- Implement`/scorecards` endpoint (https://api.staging.wormscan.io/api/v1/scorecards)
For now, the endpoint is just returning this data:
```
{
"24h_tx_count": "800"
}
```
The rest of the data will be added incrementally in the `endpoint` and should automatically be displayed in the `UI`
ref: https://github.com/wormhole-foundation/wormhole-explorer/issues/221
> feat: add scorcards endpoint

- src/components/molecules/TransactionHistoryChart/index.tsx
- src/components/molecules/TransactionHistoryChart/styles.scss
Fixes #73 #75
- Fix order in the `Latest tx graph`
- Fix labels format
> fix(73-75): order and styling in latest tx graph

- src/components/molecules/TransactionHistoryChart/index.tsx
Fixes #73 #78
- Fix labels on mobile view
- Fix label values on the `1M` view
Desktop:
https://github.com/XLabs/wormscan-ui/assets/25652943/325d6b4f-c7b6-4588-b8a8-40a770695be5
Mobile:
https://github.com/XLabs/wormscan-ui/assets/25652943/f3dfa9b3-d861-4ffe-bdfc-4a64ad983382
> fix(73-78): mobile styling & 1M values

- package.json
- src/components/molecules/Footer/index.tsx
- src/components/molecules/Footer/styles.scss
- src/components/molecules/Header/Search/index.tsx
- src/components/molecules/Header/index.tsx
- src/components/molecules/Header/styles.scss
- src/components/molecules/SearchBar/index.tsx
- src/components/molecules/SearchBar/styles.scss
- src/i18n/locales/en.js
- src/index.scss
- src/pages/Home/Hero/index.tsx
- src/pages/Home/Statistics/styles.scss
- src/pages/Home/index.tsx
- src/pages/Tx/Information/index.tsx
- src/pages/Txs/Information/index.tsx
- yarn.lock
- Remove the `Hero` section with the `Search bar`
- Add the `Search bar` component into the `Header` component
- Styles `desktop` & `mobile`
> fix: Search bar

- package.json
- src/components/organisms/Table/index.tsx
- src/i18n/locales/en.js
- src/pages/Home/TopLists/index.tsx
- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Txs/Information/index.tsx
- src/pages/Txs/Information/styles.scss
- src/pages/Txs/styles.scss
- src/utils/crypto.ts
- src/utils/date.ts
- src/utils/string.ts
- src/utils/wormhole.ts
- yarn.lock
- Add base for `Transaction Page`
*to-do*
- Implement new endpoint with the complete data as per figma [BE]
- txhash encode for Solana explorer (solscan)
> feat: add tx page base content

- src/assets/bg-404.svg
- src/assets/bg-mobile-404.svg
- src/components/molecules/Footer/index.tsx
- src/components/molecules/Footer/styles.scss
- src/components/molecules/Header/index.tsx
- src/index.scss
- src/navigation/index.tsx
- src/pages/NotFound/index.tsx
- src/pages/NotFound/styles.scss
- Remove `about us` links
- Add `Not Found` page
> feat: add NotFound page

- src/components/molecules/Header/Search/index.tsx
- src/i18n/locales/en.js
- src/navigation/index.tsx
- src/pages/SearchNotFound/index.tsx
- yarn.lock
Fixes: 104
- Add the `search by VAA ID` feature
> feat(104): Add search by VAA ID

- src/components/molecules/CrossChainChart/Chart.tsx
- src/components/molecules/CrossChainChart/StickyInfo.tsx
- src/components/molecules/CrossChainChart/index.tsx
- src/components/molecules/CrossChainChart/styles.scss
- yarn.lock
This PR implements the bottom sheet with all the destinations information for tablet and mobile devices.
https://github.com/XLabs/wormscan-ui/assets/41705567/c4d156b0-5efe-48e8-bb57-0c8e595e2614
> Implement bottom sheet for Sankeychart on mobile

- src/components/molecules/CrossChainChart/index.tsx
- src/components/molecules/Header/Search/index.tsx
- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Tx/index.tsx
> fix(142,148): Search behavior and cache

- src/components/molecules/Header/index.tsx
> fix(173): network toggle

- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Txs/index.tsx
> fix(174): uppercase txhashes and addresses

- src/pages/Txs/index.tsx
> fix(178): txs back button

- src/components/atoms/index.tsx
- src/components/molecules/Footer/index.tsx
- src/components/molecules/Footer/styles.scss
- src/i18n/locales/en.js
- Add API Doc links into the Footer element
- Fix texts
> feat: add api docs link

- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Tx/Information/RawData/index.tsx
- src/pages/Tx/Information/index.tsx
- src/pages/Tx/index.tsx
> fix: show raw vaa

- src/components/atoms/SignatureCircle/index.tsx
This PR describes the bug described by Samanta on #194
> Fix for some mobile browsers not copying signatures

- src/components/atoms/NavLink/index.tsx
- src/components/organisms/Table/styles.scss
- src/pages/Txs/Information/index.tsx
- src/pages/Txs/index.tsx
Fixes: 188, 190
- Change tx item behavior as per requirement
> fix(188-190): tx list item behavior

- src/components/organisms/Table/styles.scss
- src/pages/Tx/Information/Summary/index.tsx
- src/pages/Tx/Information/Summary/styles.scss
- src/pages/Tx/Information/index.tsx
- src/pages/Txs/Information/index.tsx
- src/pages/Txs/index.tsx
- src/utils/crypto.ts
- Origin App added in Txs & Tx detail
> AppID on Txs and Tx detail

- src/pages/Txs/Information/index.tsx
- src/utils/crypto.ts
- Infinite loading in txs when trying to go to the page we are already on, fixed.
https://github.com/XLabs/wormscan-ui/assets/88043910/8388efb7-7ae7-419b-b10b-5b7831d7438e
https://github.com/XLabs/wormscan-ui/assets/88043910/88589f1f-de9d-47b2-b711-182c16b38cb4
> Fixed navigation to current page in Txs

- src/components/atoms/Pagination/index.tsx
- src/components/atoms/Tag/index.tsx
- src/components/molecules/Footer/styles.scss
- src/components/molecules/Header/index.tsx
- src/components/molecules/Header/styles.scss
- src/index.scss
- src/navigation/index.tsx
- src/utils/scrollControl.ts
Testing the app, I found some changes to enhance the design or behavior of the page.
- expected hover on icons
- smooth scrolling when we click a link
- logo link clickable only when we are on top of it
- scrollbar doesn't move components when displayed
- removed the movement of components when we open the mobile menu
- mobile menu with 344px
- opaque background behind the mobile menu
- mobile menu closes when clicking on a link
- plain color background in mobile menu
- more padding in header navigation mobile top
- aligned links
- small details of style
https://github.com/XLabs/wormscan-ui/assets/88043910/b6cb705c-1f45-4e51-b4b0-af24cd01f078
> Mobile menu, design changes, bugs fixed, etc.

- src/pages/Home/TopLists/index.tsx
- Children with the same key, fixed.
> fix children with the same key usually in testnet

- src/utils/wormhole.ts
- fixed problem when redirecting to the Contract Address explorer
> Redirect in contract address fixed

- yarn.lock
- New version of wormscan-sdk added 0.0.19
> New version of wormscan-sdk added

- src/components/atoms/Pagination/index.tsx
- src/components/atoms/Pagination/styles.scss
- src/styles/_containers.scss
- 3 minor design issues fixed
https://github.com/XLabs/wormscan-ui/assets/88043910/db77b010-4ea3-418f-85fb-8415052a718d
https://github.com/XLabs/wormscan-ui/assets/88043910/affa008e-dd24-4a5f-a683-1fe8a64d7750
https://github.com/XLabs/wormscan-ui/assets/88043910/cee1fa0a-3e8a-4e99-9b84-4bdb3887c812
https://github.com/XLabs/wormscan-ui/assets/88043910/1d3bf2ce-8c08-4f0f-adfc-a7869e4198ad
> Fix 3 little bugs

- src/utils/environment.ts
Adds BASE automatic relayer config
> Add base relayer

- .env.production
- api.testnet.wormscan.io changed for api.testnet.wormholescan.io in testnet prod
> Url prod testnet changed

- src/pages/Tx/Information/Details/index.tsx
- src/pages/Tx/Information/Details/styles.scss
- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Tx/Information/index.tsx
- src/pages/Tx/Information/styles.scss
- src/pages/Tx/Top/index.tsx
- src/pages/Tx/index.tsx
- src/pages/Txs/index.tsx
- yarn.lock
This PR adds support for Osmosis as source chains.
> Add Osmosis sources support

- package.json
- src/components/molecules/Footer/index.tsx
> Add version to footer

- src/pages/Tx/Information/Tabs/index.tsx
https://github.com/XLabs/wormscan-ui/assets/88043910/3f1f2f16-85fe-4819-ac1a-56638f7cedc5
https://github.com/XLabs/wormscan-ui/assets/88043910/cfdf7b1a-2dff-49b7-9bf8-962776d92548
> changes in tx detail tabs mobile

- src/pages/Tx/Top/index.tsx
- src/pages/Txs/index.tsx
> fix txHash link and copyToClipboard

- src/api/search/Search.ts
- src/api/search/types.ts
- src/pages/Tx/Information/RawData/index.tsx
- src/pages/Tx/Information/index.tsx
- src/pages/Tx/index.tsx
This PR adds support to get the "Redeem txn" for CCTP txs.
> Add redeem tx support for CCTP transactions

- src/pages/Tx/Information/index.tsx
- src/pages/Tx/index.tsx
> Fix for CCTP fees

- src/utils/fetchWithRPCsFallthrough.ts
This PR solves some problems regarding transactions without a VAA emitted yet (where the API doesn't have any info yet)
- CosmWasm chains were always defaulting to 'sei' even if was another cosm chain (like terra, terra2, etc), fixed.
- When we weren't able to detect token information, we were assuming 8 decimals, added a second check where if real token info is not found, we try to get wrapped token information to try and get the decimals of the token. This fixes several cases where the 'amount' was being shown incorrectly.
- We are now trying the 'toAddress' to the native address to fix some bugs where the destination address was being shown incorrectly for some chains like Algorand.
REAL RESULT
RPCs BEFORE
RPCs AFTER
REAL RESULT
RPCs BEFORE
RPCs AFTER
> Improve tx details info coming from RPCs

- src/components/molecules/Header/index.tsx
- src/context/EnvironmentContext.tsx
- src/navigation/index.tsx
https://github.com/XLabs/wormscan-ui/assets/88043910/a53faa29-23be-41b3-aa01-16086fafc083
https://github.com/XLabs/wormscan-ui/assets/88043910/48fde510-7361-4d14-b27d-90ab40c508f9
> Fix header select and button 'Go to Bridge'

- src/api/search/types.ts
- src/components/atoms/Alert/styles.scss
- src/pages/Tx/Information/Overview/styles.scss
- src/pages/Tx/Information/RelayerOverview/styles.scss
- src/pages/Tx/Information/index.tsx
- src/pages/Tx/Information/styles.scss
- src/pages/Tx/index.tsx
- src/utils/fetchWithRPCsFallthrough.ts
- src/utils/wormhole.ts
- add finalized block and current block number when the status is in progress
don't merge until George confirms me
> Add block info on 'in progress' transaction

- src/pages/SearchNotFound/index.tsx
- src/pages/Tx/index.tsx
- When we reload the 'not found' page, try to find the tx again.
- After 20 seconds, it will try to find the transaction again.
- Fix redirect page.
https://github.com/XLabs/wormscan-ui/assets/88043910/d7cb5b25-129a-4be6-8ee4-cf5c354ccba8
> Search again when we reload the 'not found' page

- src/pages/Tx/Information/Summary/index.tsx
> fix tx status

- src/index.scss
- src/utils/fetchWithRPCsFallthrough.ts
- show the last finalized block, no the latest block
> Fix the last finalized block number, when the VAA has not been issued yet.

- src/pages/Tx/Information/Details/index.tsx
- src/pages/Tx/Information/Details/styles.scss
- src/pages/Tx/Information/Overview/styles.scss
- src/pages/Tx/Information/RelayerOverview/styles.scss
- src/pages/Tx/Information/Summary/styles.scss
- src/pages/Tx/Top/index.tsx
- src/pages/Tx/Top/styles.scss
- src/utils/string.ts
- Show all info when possible in tx details.
- Some styles fixed
> Show all info in tx details, and some styles fixed

- src/components/atoms/SignatureCircle/index.tsx
- src/pages/Tx/Information/Details/index.tsx
- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Tx/Information/RelayerOverview/index.tsx
- src/pages/Tx/Information/RelayerOverview/styles.scss
- src/pages/Tx/Top/index.tsx
- src/pages/Txs/Top/index.tsx
- src/pages/Txs/index.tsx
- src/utils/crypto.ts
- src/utils/string.ts
> Design changes in relayer tx

- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Tx/Information/RelayerOverview/index.tsx
- src/utils/crypto.ts
> Show seq in VAA ID

- src/pages/Tx/Information/Details/index.tsx
> Tx details, inline info fixed

- src/pages/Tx/Information/Summary/index.tsx
- src/pages/Tx/Information/index.tsx
- src/pages/Tx/Information/styles.scss
- src/utils/environment.ts
- src/utils/fetchWithRPCsFallthrough.ts
This PR:
- adds new statuses pills to the transactions
- removes some unnecessary code that was there
- fix some lil bugs
> Add new statuses for txs and code cleanup

- src/pages/Tx/Information/Summary/index.tsx
- src/pages/Tx/Information/index.tsx
> Better statuses logic

- src/api/search/Search.ts
- src/components/atoms/BlockchainIcon/index.tsx
- src/components/atoms/Link/index.tsx
- src/components/atoms/NavLink/index.tsx
- src/components/molecules/CrossChainChart/Chart.tsx
- src/components/molecules/CrossChainChart/StickyInfo.tsx
- src/components/molecules/CrossChainChart/chartUtils.tsx
- src/components/molecules/CrossChainChart/index.tsx
- src/components/molecules/CrossChainChart/styles.scss
- src/components/molecules/TopAssetListItem/index.tsx
- src/components/molecules/TopChainListItem/index.tsx
- src/components/molecules/TopChainListItem/styles.scss
- src/components/molecules/TransactionHistory/TransactionHistoryChart/index.tsx
- src/pages/Tx/Information/Details/index.tsx
- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Tx/Information/RelayerOverview/index.tsx
- src/pages/Tx/Information/index.tsx
- src/pages/Txs/index.tsx
- src/utils/hooks/useNavigateCustom.tsx
- src/utils/wormhole.ts
- Names for chains in testnet, added
> Names for chains in Testnet, added

- src/components/molecules/CrossChainChart/Chart.tsx
- src/components/molecules/CrossChainChart/StickyInfo.tsx
- src/components/molecules/ScoreCard/index.tsx
- src/components/molecules/TopAssetListItem/index.tsx
- src/pages/Tx/Information/index.tsx
- src/pages/Txs/index.tsx
- src/utils/number.ts
- Improved decimals in amounts.
> Improve decimals

- src/components/atoms/Select/styles.scss
- src/components/molecules/CrossChainChart/StickyInfo.tsx
- src/components/molecules/CrossChainChart/index.tsx
- src/components/molecules/CrossChainChart/styles.scss
- src/components/molecules/Header/index.tsx
- src/components/molecules/Header/styles.scss
- Select with hover
- Adjusted radius for items in the Sankey chart
- Replaced the horizontal line for an arrow in the sticky container
[More info](https://www.notion.so/xlabsxyz/Bugs-Wormholescan-b1cb398b0c474c32b196ebc65abbe0be)
> Design bugs fixed

- src/pages/Tx/Top/index.tsx
- src/utils/wormhole.ts
> SEI explorer changed

- src/components/molecules/ScoreCard/index.tsx
- src/components/molecules/ScoreCard/styles.scss
- src/i18n/locales/en.js
> Wormhole Network Stats fixed

- src/components/molecules/CrossChainChart/Chart.tsx
- src/components/molecules/CrossChainChart/StickyInfo.tsx
- src/components/molecules/CrossChainChart/styles.scss
- src/components/molecules/Footer/index.tsx
- src/components/molecules/Header/index.tsx
- src/components/molecules/TransactionHistory/TransactionHistoryChart/index.tsx
- src/components/molecules/TransactionHistory/TransactionHistoryChart/styles.scss
- src/components/molecules/WormholeBrand/index.tsx
- src/components/molecules/WormholeBrand/styles.scss
> Watermark added

- src/components/molecules/CrossChainChart/Chart.tsx
> Fix sankey chart lines

- src/components/molecules/TopAssetsChart/index.tsx
- src/components/molecules/TopAssetsChart/styles.scss
- src/pages/Home/TopAssets/styles.scss
> Details on the top 7 assets

- src/components/molecules/CrossChainChart/chartUtils.tsx
- src/components/molecules/CrossChainChart/index.tsx
- Sankey chart, items with percentage 0 fixed
https://github.com/XLabs/wormscan-ui/assets/88043910/63428189-5557-42e8-8ba2-01f8cde89820
https://github.com/XLabs/wormscan-ui/assets/88043910/1486e1f6-9a70-483f-a665-f0710876301a
> Sankey chart, items with percentage 0 fixed

- src/components/molecules/PolicyPrivacyBanner/index.tsx
- src/components/molecules/PolicyPrivacyBanner/styles.scss
- src/components/molecules/TopAssetsChart/styles.scss
- src/navigation/index.tsx
- When we have the privacy policies, uncommenting the code, we will have the banner.
- Border radius added to top 7 assets chart.
> Policy privacy banner

- src/components/molecules/Banner/styles.scss
- src/i18n/locales/en.js
> Banner margins, join us text

- src/components/organisms/Table/index.tsx
- src/components/organisms/Table/styles.scss
- src/pages/Txs/Information/index.tsx
- src/pages/Txs/index.tsx
- New loader in txs page added.
- Loader added when we change networks.
https://github.com/XLabs/wormscan-ui/assets/88043910/16801b9b-c64f-4256-852f-3d42f9001f11
https://github.com/XLabs/wormscan-ui/assets/88043910/84823c0e-f2ae-4d81-a10e-491c4b1ec975
> New loader in txs page

- package.json
- src/pages/Tx/Information/Summary/VerifyRedemption/index.tsx
- src/pages/Tx/Information/Summary/VerifyRedemption/styles.scss
- src/pages/Tx/Information/Summary/index.tsx
- src/pages/Tx/Information/index.tsx
- src/pages/Txs/Information/index.tsx
- src/pages/Txs/index.tsx
- Added link to verify token redemption in PTB.
(This task is only for cases where the Origin App is only Portal Token Bridge)
(In this case the tx was redeemed at the same time I was checking)
https://github.com/XLabs/wormscan-ui/assets/88043910/481963d7-5b2b-42aa-bc3e-b56b9d11fdab
> Added link to verify token redemption in PTB

- src/utils/wormhole.ts
> Algorand explorer changed

- package.json
- src/components/molecules/PortalStats/styles.scss
- src/components/molecules/TransactionHistory/TransactionHistoryChart/index.tsx
- src/components/molecules/TransactionHistory/TransactionHistoryChart/styles.scss
- src/components/molecules/TransactionHistory/index.tsx
- src/components/molecules/TransactionHistory/styles.scss
- src/pages/Home/Statistics/styles.scss
- src/pages/Tx/Information/Summary/VerifyRedemption/index.tsx
- src/pages/Tx/Information/Summary/VerifyRedemption/styles.scss
- src/pages/Tx/Information/Summary/styles.scss
- src/utils/crypto.ts
- src/utils/wormhole.ts
- Version updated to 1.2.3.
- Changes in stats section.
- Removed "Stable" from the CCTP origin app.
- Improved "Resume Transaction" button for low resolution.
> version up to 1.2.3 and little style changes

- .github/workflows/staging.yaml
- Added a new CI/CD workflow for the `staging` environment.
> Adding CI/CD staging workflow

- .github/workflows/production.yaml
* Added a new CI/CD workflow for the `production` environment.
> Adding CI/CD production workflow

- src/components/molecules/TransactionHistory/TransactionHistoryChart/index.tsx
- src/components/molecules/TransactionHistory/TransactionHistoryChart/styles.scss
- src/pages/Tx/Information/Summary/index.tsx
> Removed last hour in transaction history chart.

- package.json
- src/pages/Txs/index.tsx
- yarn.lock
https://github.com/XLabs/wormscan-ui/assets/88043910/abdac64e-23e1-449a-9114-b20fe9f8fc6c
> Bug when we try to change the URL manually, fixed

- src/components/molecules/StatusBadge/index.tsx
- src/components/molecules/StatusBadge/styles.scss
- src/components/organisms/Table/styles.scss
- src/consts.ts
- src/i18n/locales/en.js
- src/pages/Tx/Information/Overview/RelayerOverview/index.tsx
- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Tx/Information/Summary/index.tsx
- src/pages/Tx/Information/Summary/styles.scss
- src/pages/Tx/Information/index.tsx
- src/pages/Txs/Information/index.tsx
- src/pages/Txs/Information/styles.scss
- src/pages/Txs/index.tsx
- src/types.ts
- src/utils/date.ts
This PR implements the first iteration of the transactions page redesign, changing the texts, deleting the amount column, changing some little UI details and letting everything ready to add the status column for the upcoming operations endpoint
> Redesign Transactions Page

- src/components/atoms/Tooltip/index.tsx
- src/components/atoms/Tooltip/styles.scss
- src/components/molecules/StatusBadge/index.tsx
- src/components/molecules/StatusBadge/styles.scss
- src/components/organisms/Table/index.tsx
- src/pages/Tx/index.tsx
- src/pages/Txs/Information/index.tsx
- src/pages/Txs/index.tsx
This PR adds the "Status" and the "Type" columns to the transactions list
> Add status and type to transactions list

- src/api/guardian-network/types.ts
- src/pages/Tx/Information/index.tsx
- src/pages/Tx/index.tsx
- src/utils/fetchWithRPCsFallthrough.ts
- src/utils/wormhole.ts
- Bug with bigTxs and dailyLimit fixed.
- Changes in when to show the info of the last finalized block.
> Block numbers fixed

- src/pages/Tx/Information/RawData/index.tsx
> Reorganized Raw Data

- src/components/molecules/Header/index.tsx
- src/components/molecules/Header/styles.scss
- src/components/molecules/PortalStats/index.tsx
- src/components/molecules/PortalStats/styles.scss
- src/components/molecules/TransactionHistory/index.tsx
- src/components/molecules/WormholeStats/index.tsx
- src/components/molecules/WormholeStats/styles.scss
- Elements in header rearranged.
- Bug with the mobile Select, fixed.
> Elements in header rearranged

- src/pages/Tx/Information/index.tsx
- src/pages/Tx/index.tsx
This PR adds the COMPLETED status for relayer txns (only inside tx detail view, not on tx list)
> Add COMPLETED status to relayer txns

- src/pages/Tx/Information/Tabs/index.tsx
- src/pages/Tx/Information/index.tsx
- src/pages/Tx/Information/styles.scss
> Move NTT+Relayer button to tabs

- src/pages/Tx/Information/Details/styles.scss
- src/pages/Tx/Information/Overview/styles.scss
- src/pages/Tx/Information/RawData/styles.scss
- src/pages/Tx/Information/Summary/VerifyRedemption/styles.scss
- src/pages/Tx/Information/Summary/index.tsx
- src/pages/Tx/Information/Summary/styles.scss
- src/pages/Tx/Information/Tabs/index.tsx
- src/pages/Tx/Information/Tabs/styles.scss
- src/pages/Tx/Information/index.tsx
- src/pages/Tx/Information/styles.scss
- Tx details page reorganized.
> Tx details page reorganized

- src/pages/VaaParser/styles.scss
> Improved scrolling in vaa parser

- src/components/molecules/CrossChainChart/StickyInfo.tsx
- src/components/molecules/CrossChainChart/styles.scss
- Changed the operation of the dropdown menu in the Sankey chart details when on mobile:
1. Arrow direction.
2. Open/close functionality when clicking inside the dropdown area.
3. The menu does not close when clicking outside.
> Details in sankey chart mobile, improved

- src/components/molecules/Header/index.tsx
- src/components/molecules/Header/styles.scss
- New distribution in the mobile menu.
- The desktop distribution remains the same.
> Optimized mobile menu

- src/pages/Governance/index.tsx
- Governance page loader fixed.
https://github.com/XLabs/wormscan-ui/assets/88043910/e8400902-988b-445c-a4e4-714836aaa17a
> Governance page loader fixed

- src/api/guardian-network/types.ts
- src/pages/Tx/index.tsx
This PR fixes attestation transactions that currently can make the app crash
> Fix attestation txns

- src/pages/VaaParser/index.tsx
This PR fixes a problem where if the user collapsed and expanded the same menu a couple times, the app will crash out of memory.
That was happening because multiple events were getting attached to the same component recursively.
The fix also helped the already collapsed submenus to keep being collapsed when parent container gets opened again (for example, guardianSignatures was always showing up when the 'vaa' field was expanded, and its a giant object which is usually not looked at)
> Improve VAA Parser behavior

- src/components/molecules/Footer/styles.scss
> Footer - small changes

- src/components/organisms/Table/index.tsx
- src/pages/Governor/index.tsx
- Default order removed.
https://github.com/XLabs/wormscan-ui/assets/88043910/ade064fe-a0d6-49dc-b1fb-5c52fbebda2d
> Governor page - default order removed

- src/api/model/ChainId.ts
- src/utils/wormhole.ts
> Chain Amoy added

- src/components/atoms/Tooltip/index.tsx
- src/components/atoms/Tooltip/styles.scss
- src/pages/Txs/Information/Filters/index.tsx
- src/pages/Txs/Information/Filters/styles.scss
- Tooltips added in txs filters.
- Tooltips mobile fixed.
[Sami's comment](https://github.com/XLabs/wormscan-ui/issues/580#issuecomment-2077107231)
> Tooltips added in txs filters

- src/pages/Tx/index.tsx
https://github.com/XLabs/wormscan-ui/assets/88043910/600f9f62-76db-4f7d-9048-04f4e0beba2e
> Tx status fixed

- src/pages/Tx/index.tsx
> fix txHash explorer URL

- src/components/organisms/Table/index.tsx
- src/pages/Governor/index.tsx
- Default view of the governor page, changed.
> Default view of the governor page

- src/pages/Tx/Information/AdvancedView/Details/RelayerDetails/index.tsx
- src/pages/Tx/Information/AdvancedView/index.tsx
- src/pages/Tx/Information/Overview/RelayerOverview/index.tsx
- src/pages/Tx/index.tsx
- src/utils/genericRelayerVaaUtils.ts
This PR changes the Overview UI Layout for Standard Relayer txns
> UI Changes for Standard Relayer txns

- src/pages/Txs/Information/Filters/index.tsx
- src/utils/environment.ts
- src/utils/metaMaskUtils.ts
This PR adds the configs needed for RPCs and Metamask stuff for Mantle.
> Add Mantle RPCs config

- src/components/atoms/BlockchainIcon/index.tsx
- src/components/atoms/MaintenanceMessage/index.tsx
- src/layouts/BaseLayout/index.tsx
- It's just a test message to test the new design.
> Show maintenance message

- src/pages/Governor/index.tsx
- src/pages/Governor/styles.scss
> Sort button changed

- src/api/guardian-network/types.ts
- src/components/molecules/ProtocolsStats/index.tsx
> NTT added in Featured Applications

- src/components/molecules/ProtocolsStats/index.tsx
> Not show incomplete info in stats

- src/pages/Governor/index.tsx
- src/pages/Governor/styles.scss
- src/utils/governorUtils.tsx
- Tooltips added in mobile.
- Change in how the percentage bar works.
- Cleaner code.
> Little changes in Governor page

- src/components/atoms/BlockchainIcon/index.tsx
- src/components/molecules/ChainActivity/index.tsx
- src/components/molecules/ChainActivity/styles.scss
- src/components/molecules/Header/index.tsx
- src/components/molecules/Header/styles.scss
> Header and Chain activity - fixes

- src/components/atoms/JsonText/index.tsx
- src/components/atoms/JsonText/styles.scss
- src/components/molecules/Header/Search/index.tsx
- src/components/molecules/Header/index.tsx
- src/components/molecules/Header/styles.scss
- src/icons/generic/AlertTriangle/index.tsx
- src/icons/generic/InfoCircleIcon/index.tsx
- src/icons/generic/SearchIcon/index.tsx
- src/icons/generic/TriangleDownIcon/index.tsx
- src/icons/generic/index.tsx
- src/layouts/BaseLayout/index.tsx
- src/pages/VaaParser/CopyContent.tsx
- src/pages/VaaParser/Input.tsx
- src/pages/VaaParser/index.tsx
- src/pages/VaaParser/styles.scss
- Vaa parser redesign.
- New header style.
> Vaa parser redesign

- src/components/atoms/MaintenanceMessage/style.scss
- src/components/molecules/ChainActivity/Calendar/index.tsx
- src/components/molecules/ChainActivity/index.tsx
- src/components/molecules/ChainActivity/styles.scss
- src/components/molecules/StatusBadge/index.tsx
- src/components/molecules/WormholeStats/styles.scss
- src/index.scss
- src/pages/PrivacyPolicy/index.tsx
- src/pages/TermsOfUse/index.tsx
- src/pages/TermsOfUse/styles.scss
- src/pages/Txs/Information/Filters/index.tsx
- src/pages/Txs/Information/Filters/styles.scss
- src/utils/chainActivityUtils.ts
- Fixes in chains activity chart.
- Other minor bugs fixed.
> Chains activity - fixes

- package.json
- src/pages/Tx/Information/Overview/RelayerOverview/index.tsx
- src/pages/Tx/Information/Overview/styles.scss
- src/pages/Tx/index.tsx
This PR adds support in prod for redeliveries
> Hotfix: SR Redeliveries support

- .github/workflows/staging.yaml
- package.json
- src/api/guardian-network/GuardianNetwork.ts
- src/api/guardian-network/types.ts
- src/components/molecules/CrossChainChart/index.tsx
- src/components/molecules/ProtocolsStats/index.tsx
- src/consts.ts
- src/i18n/locales/en.js
- src/pages/Tx/Information/index.tsx
- src/pages/Tx/index.tsx
- src/pages/Txs/Information/Filters/index.tsx
- src/pages/Txs/index.tsx
- src/utils/wh-portico-rpc.ts
> Prod release

- src/components/molecules/CrossChainChart/chartUtils.tsx
> Sankey fixed PROD

- src/components/molecules/Footer/index.tsx
- src/components/molecules/Header/index.tsx
- src/layouts/BaseLayout/index.tsx
- src/pages/PrivacyPolicy/index.tsx
- src/pages/TermsOfUse/index.tsx
- src/pages/TermsOfUse/styles.scss
- Improvements in TOU.
- TOU text repositioned in the footer.
> TOU changes

- src/pages/Tx/Information/index.tsx
> PROD - show tx fixed

- src/components/molecules/ChainActivity/Calendar/index.tsx
- src/components/molecules/ChainActivity/index.tsx
- Protocol filter removed.
- Texts changed.
> Chain activity - protocol filter removed

- src/components/atoms/Select/index.tsx
- src/components/atoms/Select/styles.scss
- src/pages/Txs/Information/Filters/index.tsx
This PR fixes gateway problems in the Transactions page.
> Gateway fixes in Transactions page

- .env.development
- .env.production
- package.json
- src/assets/copyIcon.svg
- src/assets/triangleDownIcon.svg
- src/components/molecules/Footer/index.tsx
- src/components/molecules/Header/index.tsx
- src/components/molecules/ProtocolsStats/index.tsx
- src/navigation/index.tsx
- src/pages/ApiDoc/index.tsx
- src/pages/ApiDoc/styles.scss
- yarn.lock
- API DOC added and redesigned.
> API DOC page - added

- package.json
- src/pages/Tx/index.tsx
> SR tx budget fixed

- src/components/organisms/SearchNotFound/styles.scss
- src/components/organisms/Table/styles.scss
- src/pages/Governor/styles.scss
> Fixed styles

- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Tx/Information/Overview/styles.scss
- src/pages/Tx/Information/ProgressView/index.tsx
- src/pages/Tx/Information/ProgressView/styles.scss
- src/pages/Tx/Information/Summary/index.tsx
- src/pages/Tx/Information/index.tsx
- src/utils/txPageUtils.tsx
- src/utils/wh-portico-rpc.ts
- Adds tooltips to section titles in tx detail
- Changes some titles for better clarity
- Moves the Progress section to a new tab
> Last enhancements

- src/components/atoms/ProtocolIcon/index.tsx
- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Tx/Information/Overview/styles.scss
> Portal logo changed - Info icon added in tx page

- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Tx/Information/Overview/styles.scss
- src/pages/Tx/Information/ProgressView/index.tsx
- Reorganization of the elements.
> Tx details - reorganization

- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Tx/Information/Overview/styles.scss
- src/pages/Tx/Information/ProgressView/index.tsx
- src/pages/Tx/Information/ProgressView/styles.scss
> Tx details - latest reorganization changes

- src/components/atoms/AddToMetaMaskBtn/index.tsx
- src/components/atoms/BlockchainIcon/index.tsx
- src/components/molecules/CrossChainChart/Chart.tsx
- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Tx/Information/Overview/styles.scss
- src/pages/Tx/Information/index.tsx
#827 
- Unified logic to display the Metamask button.
- Style mobile fixed.
> Tx detail - styles and logic improved

- src/components/molecules/CrossChainChart/Chart.tsx
- src/components/molecules/CrossChainChart/styles.scss
- src/components/molecules/TopAssetsChart/index.tsx
#844 
- Do not show pagination when there are not enough items.
> Cross-Chain Activity - pagination fixed

- src/components/molecules/CrossChainChart/styles.scss
- src/components/organisms/ChainActivity/Calendar.tsx
- src/components/organisms/ChainActivity/index.tsx
#842 
- Reset button fixed.
- Close calendar when we select a range date.
- Styles fixed.
> Chains chart - little fixes

- src/pages/Tx/Information/Overview/styles.scss
> Tx detail mobile fixed

- src/consts.ts
This PR fixes guardian signatures
> Fix Signatures

- src/api/guardian-network/types.ts
- src/pages/Tx/Information/AdvancedView/index.tsx
- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Tx/Information/index.tsx
- src/pages/Txs/Information/Filters/index.tsx
- src/utils/crypto.ts
[WS-35](https://xlabs-xyz.atlassian.net/browse/WS-35)
- Select all mayan protocols when selecting mayan.
- Repositioned action row.
- Redirect to advanced when we select the action number.
- N/A removed.
[WS-35]: https://xlabs-xyz.atlassian.net/browse/WS-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Tx detail - changes

- src/components/organisms/ChainActivity/index.tsx
- src/pages/Analytics/WToken/RecentTransactions.tsx
> W token page fixed

- src/pages/ApiDoc/index.tsx
- src/pages/ApiDoc/styles.scss
[WS-34](https://xlabs-xyz.atlassian.net/browse/WS-34?focusedCommentId=10199)
[WS-34]: https://xlabs-xyz.atlassian.net/browse/WS-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> API DOC - new deprecated endpoints

- src/components/molecules/CrossChainChart/index.tsx
- src/components/molecules/ProtocolsActivity/index.tsx
- src/components/molecules/ProtocolsActivity/styles.scss
- src/components/organisms/ChainActivity/index.tsx
- src/components/organisms/ChainActivity/styles.scss
- src/components/organisms/TokenActivity/Chart.tsx
- src/components/organisms/TokenActivity/styles.scss
- src/pages/Analytics/WToken/TransfersOverTime.tsx
- src/pages/Analytics/WToken/index.tsx
- src/pages/Analytics/WToken/styles.scss
- src/utils/chainActivityUtils.ts
- src/utils/date.ts
[WS-73](https://xlabs-xyz.atlassian.net/browse/WS-73)
- Date range added in tooltips.
- Bug fixed in Chains chart.
https://github.com/user-attachments/assets/bdd1a1fc-017a-4cc4-af58-a22c2cabda3e
[WS-73]: https://xlabs-xyz.atlassian.net/browse/WS-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Date range added in tooltips

- README.md
- src/components/molecules/ProtocolsStats/index.tsx
> Fixed API DOC URL in README - Fixed loader in protocols

- src/components/molecules/TopAssets/index.tsx
- src/i18n/locales/en.js
- src/pages/Tx/Information/index.tsx
[WS-29](https://xlabs-xyz.atlassian.net/browse/WS-29)
[WS-29]: https://xlabs-xyz.atlassian.net/browse/WS-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Testnet - Advanced Page as default view

- src/icons/generic/ArrowUpRightIcon/index.tsx
- src/pages/Analytics/WToken/Summary.tsx
- src/pages/Analytics/WToken/styles.scss
> Contract icon fixed in W Token page

- src/api/guardian-network/types.ts
- src/components/molecules/StatusBadge/index.tsx
- src/consts.ts
- src/pages/Analytics/WToken/RecentTransactions.tsx
- src/pages/Analytics/WToken/index.tsx
- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Tx/Information/ProgressView/index.tsx
- src/pages/Tx/Information/Summary/index.tsx
- src/pages/Tx/Information/index.tsx
- src/pages/Tx/index.tsx
- src/pages/Txs/index.tsx
- src/utils/fetchWithRPCsFallthrough.ts
- src/utils/txPageUtils.tsx
[WS-107](https://xlabs-xyz.atlassian.net/browse/WS-107)
[WS-107]: https://xlabs-xyz.atlassian.net/browse/WS-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Show lowercase status in advanced view

- src/components/molecules/Calendar/index.tsx
- src/components/molecules/ProtocolsStats/index.tsx
- src/components/molecules/ProtocolsStats/styles.scss
- src/pages/ApiDoc/index.tsx
- src/pages/Tx/Information/Summary/GetRedeem/index.tsx
- src/pages/Tx/Information/Summary/GetRedeem/styles.scss
[WS-89](https://xlabs-xyz.atlassian.net/browse/WS-89) [WS-93](https://xlabs-xyz.atlassian.net/browse/WS-93) [WS-67](https://xlabs-xyz.atlassian.net/browse/WS-67)
- TVL added in protocols.
- Some paths fixed in API DOC.
- Date range little changes.
- Tooltip removed in GetRedeem component.
[WS-89]: https://xlabs-xyz.atlassian.net/browse/WS-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WS-93]: https://xlabs-xyz.atlassian.net/browse/WS-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WS-67]: https://xlabs-xyz.atlassian.net/browse/WS-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TVL added in protocols and api doc fixed

- src/analytics.ts
- src/components/atoms/Fullscreenable/index.tsx
- src/components/molecules/CrossChainChart/index.tsx
- src/components/molecules/ProtocolsActivity/index.tsx
- src/components/molecules/ProtocolsStats/index.tsx
- src/components/molecules/TopAssets/index.tsx
- src/components/molecules/WormholeStats/index.tsx
- src/components/organisms/ChainActivity/index.tsx
- src/components/organisms/Table/index.tsx
- src/components/organisms/TokenActivity/Chart.tsx
- src/components/organisms/TokenActivity/index.tsx
- src/pages/Analytics/WToken/RecentTransactions.tsx
- src/pages/Analytics/WToken/TransfersOverTime.tsx
- src/pages/Analytics/WToken/index.tsx
- src/pages/Governor/index.tsx
- src/pages/Txs/Information/Filters/index.tsx
- src/pages/Txs/Top/index.tsx
This PR adds all the analytics mentioned in [WS-117](https://xlabs-xyz.atlassian.net/browse/WS-117) that weren't trackable with what we already had
[WS-117]: https://xlabs-xyz.atlassian.net/browse/WS-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add moar analytics

- src/components/molecules/Calendar/index.tsx
- src/components/molecules/Calendar/styles.scss
- src/pages/Txs/Information/Filters/index.tsx
- Possibility to select the year in the calendar.
- "custom" button operation changed.
- Fixes in filters.
https://github.com/user-attachments/assets/10ad3b23-934e-4aa5-848b-35a6140b57bd
https://github.com/user-attachments/assets/b9c6172a-3007-48cd-be89-590068ab3a07
[WS-67]: https://xlabs-xyz.atlassian.net/browse/WS-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Filters in tx list fixed

- src/pages/Analytics/NTT/NTTToken/ByChain.tsx
- src/pages/Analytics/NTT/NTTToken/RecentTransactions.tsx
- src/pages/Analytics/NTT/NTTToken/TopAddresses.tsx
- src/pages/Analytics/NTT/NTTToken/TransfersOverTime.tsx
- src/pages/Analytics/NTT/NTTToken/index.tsx
- src/pages/Analytics/NTT/NTTToken/styles.scss
- src/pages/Analytics/NTT/TokensTradedList.tsx
[WS-127](https://xlabs-xyz.atlassian.net/browse/WS-127)
[WS-127]: https://xlabs-xyz.atlassian.net/browse/WS-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NTT page - changes and fixes

- src/pages/Txs/index.tsx
- src/utils/wormhole.ts
[WS-145](https://xlabs-xyz.atlassian.net/browse/WS-145)
[WS-145]: https://xlabs-xyz.atlassian.net/browse/WS-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Prevent unexpected errors when a chain is not supported

- src/components/atoms/Pagination/styles.scss
- src/components/molecules/WormholeStats/styles.scss
- src/components/organisms/Table/index.tsx
- src/components/organisms/Table/styles.scss
- src/pages/Analytics/NTT/NTTToken/Metrics.tsx
- src/pages/Analytics/NTT/NTTToken/RecentTransactions.tsx
- src/pages/Analytics/NTT/NTTToken/Summary.tsx
- src/pages/Analytics/NTT/NTTToken/TopHolders.tsx
- src/pages/Analytics/NTT/NTTToken/index.tsx
- src/pages/Analytics/NTT/NTTToken/styles.scss
- src/pages/Analytics/NTT/Stats.tsx
- src/pages/Analytics/NTT/TokensTradedList.tsx
- src/pages/Analytics/NTT/index.tsx
- src/pages/Analytics/NTT/styles.scss
- src/pages/Submit/styles.scss
- src/pages/Txs/Information/index.tsx
- src/pages/Txs/Information/styles.scss
- src/pages/Txs/index.tsx
- src/utils/date.ts
- src/utils/hooks/useWindowSize/index.tsx
- src/utils/nttUtils.ts
NTT page & Txs list improvements [WS-127](https://xlabs-xyz.atlassian.net/browse/WS-127) [WS-137](https://xlabs-xyz.atlassian.net/browse/WS-137) [WS-158](https://xlabs-xyz.atlassian.net/browse/WS-158)
- NTT page changes and fixes.
- Txs list: full date for days before "1 day ago" and styles changes.
- Pagination blocked fixed.
- Tooltips added.
[WS-127]: https://xlabs-xyz.atlassian.net/browse/WS-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WS-137]: https://xlabs-xyz.atlassian.net/browse/WS-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WS-158]: https://xlabs-xyz.atlassian.net/browse/WS-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NTT page & Txs list improvements

- src/components/molecules/ProtocolsActivity/index.tsx
- src/components/molecules/ProtocolsActivity/styles.scss
- src/components/molecules/ProtocolsStats/styles.scss
- src/components/organisms/ChainActivity/index.tsx
- src/components/organisms/ChainActivity/styles.scss
- src/components/organisms/TokenActivity/Chart.tsx
- src/components/organisms/TokenActivity/styles.scss
- src/pages/Analytics/NTT/NTTToken/TransfersOverTime.tsx
- src/pages/Analytics/NTT/NTTToken/styles.scss
- src/pages/Analytics/NTT/index.tsx
- src/utils/date.ts
[WS-91](https://xlabs-xyz.atlassian.net/browse/WS-91)
- Show date range in charts.
- Fixes.
[WS-91]: https://xlabs-xyz.atlassian.net/browse/WS-91?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Show date in charts

- src/api/native-token-transfer/NttApi.ts
- src/pages/Analytics/NTT/NTTToken/Summary.tsx
- src/utils/cryptoToolkit.ts
- src/utils/environment.ts
> CoinMarketCap as fallback for NTT info

- src/components/atoms/Tooltip/index.tsx
- src/components/atoms/Tooltip/styles.scss
- src/components/molecules/StatusBadge/index.tsx
- src/components/molecules/StatusBadge/styles.scss
- src/consts.ts
- src/icons/generic/ClockIcon/index.tsx
- src/pages/Analytics/NTT/NTTToken/index.tsx
- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Tx/Information/Overview/styles.scss
- src/pages/Tx/Information/ProgressView/index.tsx
- src/pages/Tx/Information/ProgressView/styles.scss
- src/pages/Tx/Information/index.tsx
- src/pages/Tx/index.tsx
- src/pages/Txs/index.tsx
- src/utils/date.ts
- src/utils/txPageUtils.tsx
---
---
---
---
[WS-136]: https://xlabs-xyz.atlassian.net/browse/WS-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Progress view improved

- src/pages/ApiDoc/index.tsx
- Added info to correctly make calls to endpoints.
[WS-129]: https://xlabs-xyz.atlassian.net/browse/WS-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> API Doc fixes

- src/components/organisms/TokenActivity/index.tsx
- src/pages/Governor/index.tsx
[WS-187](https://xlabs-xyz.atlassian.net/browse/WS-187)
[WS-187]: https://xlabs-xyz.atlassian.net/browse/WS-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Governor page - default order DESC by Daily Limit

- src/components/atoms/Select/index.tsx
- src/components/organisms/ChainActivity/index.tsx
- src/components/organisms/ChainActivity/styles.scss
- src/pages/Txs/Information/Filters/index.tsx
- src/pages/Txs/Information/Filters/styles.scss
- src/pages/Txs/Information/index.tsx
- src/pages/Txs/index.tsx
[WS-172](https://xlabs-xyz.atlassian.net/browse/WS-172) [WS-173](https://xlabs-xyz.atlassian.net/browse/WS-173)
- Handle filters when pressing enter.
- Show complete dates in the date range.
[WS-172]: https://xlabs-xyz.atlassian.net/browse/WS-172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WS-173]: https://xlabs-xyz.atlassian.net/browse/WS-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Filters improved

- src/pages/Analytics/NTT/TokensTradedList.tsx
- src/pages/Analytics/NTT/index.tsx
- src/utils/nttUtils.ts
> New columns order - NTT table

- src/pages/Tx/index.tsx
- src/utils/cryptoToolkit.ts
- src/utils/fetchWithRPCsFallthrough.ts
- src/utils/wormhole.ts
This PR adds support for Aptos manual CCTP transactions
> Add Aptos CCTP support

- src/pages/Tx/index.tsx
- Info was being replaced with that obtained with rpcs
Enter any in progress tx of Standard Relayer + NTT to see it:
https://wormholescan.io/#/txs?appId=GENERIC_RELAYER
https://github.com/user-attachments/assets/3449f7b8-4d9d-4245-b499-c3f6633996f9
> GR + NTT details fixed

- src/pages/Analytics/NTT/NTTToken/RecentTransactions.tsx
- src/pages/Analytics/NTT/NTTToken/Summary.tsx
- src/pages/PrivacyPolicy/index.tsx
- src/pages/TermsOfUse/index.tsx
- src/pages/TermsOfUse/styles.scss
- Preventing errors in the NTT page.
- Fixed styles in terms of use.
> NTT page fixed

- src/consts.ts
- src/utils/filterUtils.tsx
- src/utils/wormhole.ts
[WS-299](https://xlabs-xyz.atlassian.net/browse/WS-299) Seievm config
[WS-302](https://xlabs-xyz.atlassian.net/browse/WS-302) BSC supported for NTT
[WS-299]: https://xlabs-xyz.atlassian.net/browse/WS-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WS-302]: https://xlabs-xyz.atlassian.net/browse/WS-302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Seievm config & BSC supported for NTT

- src/components/atoms/ProtocolIcon/index.tsx
- src/consts.ts
- src/pages/Tx/Information/Overview/index.tsx
- src/pages/Txs/Information/styles.scss
- src/pages/Txs/index.tsx
- src/utils/crypto.ts
- src/utils/txPageUtils.tsx
- src/utils/wormhole.ts
This PR adds testnet URL for bigdipper, fixes osmosis testnet URLs, adds M_PORTAL protocol icon, and fixes Noble's URLs
> Gateway and Noble fixes

- src/components/organisms/TokenActivity/index.tsx
- Keep the same token selected only when the user does it manually
> Top tokens transferred changes

- src/pages/Tx/index.tsx
Transaction details view with multiple VAAs will now sort depending on sequence, so latest txns first
> Sort by sequence in tx detail

- src/utils/environment.ts
- src/utils/genericRelayerVaaUtils.ts
> Fix Monad SR transactions

- src/api/native-token-transfer/NttApi.ts
- src/pages/Analytics/NTT/index.tsx
- src/pages/Tx/Information/index.tsx
[WS-346](https://xlabs-xyz.atlassian.net/browse/WS-346)
- Overview set as default view in TX details, mainnet and testnet.
- Removed an extra API call for redundant data.
[WS-346]: https://xlabs-xyz.atlassian.net/browse/WS-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Overview as default & Removed extra request for redundant data

- src/pages/Tx/Information/Overview/index.tsx
> Fix error when not having appIds
